import type { AppConfig } from './types'

// Defaults follow the PRD "Configuration defaults" table. Items the PRD leaves
// open (bin edges, verdict colours, tie handling) are marked "placeholder" in
// the How scoring works tab so they are agreed rather than assumed.

export const CONFIG_VERSION = 1

export const DEFAULT_CONFIG: AppConfig = {
  version: CONFIG_VERSION,

  scoring: {
    weights: { lead: 1, fill: 1, onTime: 1 },
    tieMethod: 'min',
    missingRank: 'worst',
    rankPopulation: 'minPoLines',
    leadStat: 'mean',
    capFillAtOrdered: false,
  },

  onTime: {
    clock: 'PO_GRPO',
    requiredDateCounts: true,
    fallbackAllowance: { Local: 30, Import: 90 },
    allowances: {},
  },

  verdicts: {
    lead: {
      fastMultiple: 0.8,
      fast: { label: 'Fast', tone: 'emerald' },
      typical: { label: 'Typical', tone: 'neutral' },
      slow: { label: 'Slow', tone: 'red' },
    },
    fill: {
      completeAt: 99.5,
      complete: { label: 'Complete', tone: 'emerald' },
      near: { label: 'Near full', tone: 'neutral' },
      short: { label: 'Short', tone: 'red' },
    },
    onTime: {
      onTimeAt: 90,
      onTime: { label: 'On time', tone: 'emerald' },
      mixed: { label: 'Mixed', tone: 'amber' },
      late: { label: 'Late', tone: 'red' },
    },
    noData: 'No data',
  },

  issues: {
    latePct: 60,
    slowMultiple: 1.25,
    shortFillPct: 95,
    shortFillSeriousPct: 80,
    returnsPct: 0,
    stillInUseDays: 60,
    thinSample: 5,
    flags: {
      late: { label: 'Late', reason: 'On time {value}, below {threshold}', enabled: true },
      slow: { label: 'Slow', reason: 'Lead time {value}, above {threshold} ({multiple} × scope median {median})', enabled: true },
      shortFill: { label: 'Short fill', reason: 'Order fill {value}, below {threshold}', enabled: true },
      returns: { label: 'Returns', reason: 'Returned {value} of net received qty, above {threshold}', enabled: true },
    },
    severity: {
      serious: { label: 'Serious', tone: 'red' },
      warning: { label: 'Warning', tone: 'amber' },
    },
  },

  review: { minPoLines: 10, minValue: 50_000_000, combine: 'any' },

  spend: { topSharePct: 80 },

  quartiles: {
    tones: ['emerald', 'neutral', 'neutral', 'red'],
    labels: ['Best quarter in scope', 'Second quarter', 'Third quarter', 'Worst quarter in scope'],
  },

  bins: {
    prToRequired: { Local: [7, 14, 30, 60], Import: [14, 30, 60, 90] },
    prToPo: { Local: [1, 3, 7, 14, 30], Import: [3, 7, 14, 30, 60] },
    poToGrpo: { Local: [7, 14, 21, 30, 60], Import: [14, 30, 45, 60, 90] },
  },

  filters: {
    minPoLinesOptions: [1, 3, 5, 10],
    minPoLinesDefault: 3,
    stillInUseDefault: true,
    pageSizes: [10, 20, 50],
    pageSizeDefault: 20,
  },

  tiles: {
    scorecard: [
      {
        id: 'vendors', label: 'Vendors in scope', metric: 'vendorsInScope', format: 'int',
        hint: '{vendorsRanked} ranked · {reviewVendors} above review threshold',
        tooltip: 'Distinct vendors with at least one PO line in the selected vendor group and material path.',
        accent: 'neutral', visible: true,
      },
      {
        id: 'value', label: 'Purchase value', metric: 'purchaseValue', format: 'money',
        hint: '{poLines} PO lines · {top80Vendors} vendors make {topSharePct} of spend',
        tooltip: 'Σ PO line total (local currency) in scope. SAP: POR1.LineTotal.',
        accent: 'neutral', visible: true,
      },
      {
        id: 'lead', label: 'Average lead time', metric: 'avgLeadTime', format: 'days',
        hint: 'Scope median of vendors {scopeMedianLead}',
        tooltip: 'Mean clock days over receipts with a PO link in scope. The scope median is the median of vendor lead times and anchors the Fast / Typical / Slow verdict.',
        accent: 'neutral', visible: true,
      },
      {
        id: 'ontime', label: 'On-time rate', metric: 'onTimeRate', format: 'pct',
        hint: '{linkedReceipts} receipts measured',
        tooltip: 'On-time receipts ÷ receipts with a PO link, over the whole scope (receipt-weighted).',
        accent: 'neutral', visible: true,
      },
      {
        id: 'fill', label: 'Order fill', metric: 'orderFill', format: 'pct',
        hint: 'PO lines with at least one receipt',
        tooltip: 'Σ received ÷ Σ ordered, over PO lines that have at least one receipt, so orders still on their way do not look short.',
        accent: 'neutral', visible: true,
      },
    ],
    issues: [
      {
        id: 'inuse', label: 'Problem vendors still in use', metric: 'problemInUse', format: 'int',
        hint: '{problemInUseSerious} serious',
        tooltip: 'Vendors with at least one issue flag whose last PO is within the still-in-use window of the newest PO in the data.',
        accent: 'red', visible: true,
      },
      {
        id: 'notused', label: 'Problem vendors no longer used', metric: 'problemNotUsed', format: 'int',
        hint: 'Last PO older than the still-in-use window',
        tooltip: 'Flagged vendors that have not been ordered from within the still-in-use window.',
        accent: 'neutral', visible: true,
      },
      {
        id: 'spend', label: 'Spend with problem vendors', metric: 'problemSpend', format: 'money',
        hint: '{problemSpendShare} of scope spend',
        tooltip: 'Σ PO line total of vendors carrying at least one flag, and its share of all spend in scope.',
        accent: 'amber', visible: true,
      },
      {
        id: 'common', label: 'Most common issue', metric: 'mostCommonIssue', format: 'text',
        hint: '{mostCommonIssueCount} vendors',
        tooltip: 'The issue flag carried by the most vendors in scope.',
        accent: 'neutral', visible: true,
      },
    ],
  },

  columns: {
    scorecard: [
      { id: 'rank', label: '#', visible: true, tip: { purpose: 'Overall rank in scope, 1 is the best vendor.', formula: 'Order of Score ascending; ties broken by higher purchase value.', source: 'Computed' } },
      { id: 'vendor', label: 'Vendor', visible: true, tip: { purpose: 'Vendor name, code and group. Dot = above review threshold. "thin" = fewer receipts than the thin-sample guard.', formula: '—', source: 'OCRD.CardName, OCRD.CardCode, OCRG.GroupName' } },
      { id: 'lead', label: 'Lead time', visible: true, tip: { purpose: 'How long the vendor takes on the configured clock.', formula: 'Σ clock days of receipts with a PO link ÷ number of those receipts', source: 'OPDN.DocDate − OPOR.DocDate (or OPRQ.DocDate), linked by PDN1.BaseEntry/BaseLine' } },
      { id: 'fill', label: 'Fill', visible: true, tip: { purpose: 'How much of what was ordered actually arrived.', formula: 'Σ received on PO lines with ≥ 1 receipt ÷ Σ ordered on those lines', source: 'PDN1.Quantity, POR1.Quantity' } },
      { id: 'onTime', label: 'On time', visible: true, tip: { purpose: 'Share of receipts that arrived inside the material allowance or by the PR required date.', formula: 'On-time receipts ÷ receipts with a PO link', source: 'OPDN.DocDate, OPOR.DocDate, PRQ1.PQTReqDate' } },
      { id: 'score', label: 'Score', visible: true, tip: { purpose: 'Weighted sum of criterion ranks. Lower is better.', formula: 'w_lead × rank_lead + w_fill × rank_fill + w_ontime × rank_ontime', source: 'Computed' } },
      { id: 'issues', label: 'Issues', visible: true, tip: { purpose: 'Issue flags raised by the Configuration issue rules.', formula: 'Late, Slow, Short fill, Returns (see How scoring works)', source: 'Computed' } },
      { id: 'lastPo', label: 'Last PO', visible: true, tip: { purpose: 'Most recent PO date with this vendor in scope.', formula: 'max(PO date)', source: 'OPOR.DocDate' } },
      { id: 'value', label: 'Value', visible: true, tip: { purpose: 'Purchase value in scope.', formula: 'Σ PO line total', source: 'POR1.LineTotal' } },
      { id: 'cumShare', label: 'Cum. share', visible: true, tip: { purpose: 'Running share of scope spend when vendors are sorted by value, largest first.', formula: 'Σ value of this and larger vendors ÷ scope value', source: 'Computed' } },
      { id: 'poLines', label: 'PO lines', visible: true, tip: { purpose: 'Number of PO lines in scope.', formula: 'count(PO lines)', source: 'POR1' } },
      { id: 'receipts', label: 'Receipts', visible: true, tip: { purpose: 'Number of GRPO lines in scope, with or without a PO link.', formula: 'count(GRPO lines)', source: 'PDN1' } },
    ],
    issues: [
      { id: 'vendor', label: 'Vendor', visible: true, tip: { purpose: 'Vendor name, code and group.', formula: '—', source: 'OCRD, OCRG' } },
      { id: 'flags', label: 'Issues', visible: true, tip: { purpose: 'Each flag with the reason in words.', formula: 'Issue rules on the Configuration tab', source: 'Computed' } },
      { id: 'lastPo', label: 'Last PO', visible: true, tip: { purpose: 'Most recent PO date and days before the newest PO in the data.', formula: 'newest PO date in data − vendor last PO date', source: 'OPOR.DocDate' } },
      { id: 'onTime', label: 'On time', visible: true, tip: { purpose: 'Share of receipts on time.', formula: 'On-time receipts ÷ receipts with a PO link', source: 'OPDN, OPOR, PRQ1' } },
      { id: 'lead', label: 'Lead time', visible: true, tip: { purpose: 'Average clock days.', formula: 'Σ clock days ÷ receipts with a PO link', source: 'OPDN, OPOR' } },
      { id: 'fill', label: 'Fill', visible: true, tip: { purpose: 'Received against ordered on lines with a receipt.', formula: 'Σ received ÷ Σ ordered', source: 'PDN1, POR1' } },
      { id: 'returns', label: 'Returns', visible: true, tip: { purpose: 'Returned quantity against net received.', formula: 'Σ returned qty ÷ (Σ received − Σ returned)', source: 'RPD1.Quantity, PDN1.Quantity' } },
      { id: 'openRows', label: 'Open rows', visible: true, tip: { purpose: 'PO lines not yet fully received.', formula: 'count(PO lines with received < ordered)', source: 'POR1.OpenQty or computed' } },
      { id: 'value', label: 'Value', visible: true, tip: { purpose: 'Purchase value in scope.', formula: 'Σ PO line total', source: 'POR1.LineTotal' } },
      { id: 'receipts', label: 'Receipts', visible: true, tip: { purpose: 'GRPO lines in scope.', formula: 'count(GRPO lines)', source: 'PDN1' } },
    ],
  },

  format: {
    locale: 'id-ID',
    currencyPrefix: 'Rp ',
    moneyUnits: [
      { at: 1e12, suffix: ' T' },
      { at: 1e9, suffix: ' M' },
      { at: 1e6, suffix: ' jt' },
      { at: 1e3, suffix: ' rb' },
    ],
    moneyDecimals: 1,
    pctDecimals: 1,
    daysDecimals: 1,
    dateStyle: 'dd MMM yyyy',
    daysSuffix: ' d',
  },

  data: {
    fieldAliases: {
      flat: {
        vendorCode: ['Kode Vendor', 'Vendor Code', 'CardCode', 'BP Code'],
        vendorName: ['Nama Vendor', 'Vendor Name', 'CardName', 'BP Name'],
        vendorGroup: ['Vendor Group', 'GroupName', 'BP Group'],
        level1: ['Level 1 (Item Group)', 'Level 1', 'Item Group', 'ItmsGrpNam', 'U_Level1'],
        level2: ['Cat2 Name', 'Level 2', 'U_Level2'],
        level3: ['Cat3 Name', 'Level 3', 'U_Level3'],
        level4: ['Cat4 Name', 'Level 4', 'U_Level4'],
        prDoc: ['PR DocNum', 'PR No', 'PR Number'],
        prDate: ['PR Date'],
        prRequiredDate: ['PR Required Date', 'Required Date', 'PQTReqDate'],
        poDoc: ['PO DocNum', 'PO No', 'PO Number'],
        poLine: ['PO LineNum', 'PO Line'],
        poDate: ['PO Date'],
        itemCode: ['Item Code', 'ItemCode'],
        itemName: ['Item Description', 'Item Name', 'Dscription'],
        qtyOrdered: ['PO Qty', 'Qty Ordered'],
        lineValue: ['Line Total', 'LineTotal', 'Total (LC)'],
        grpoDoc: ['GRPO DocNum', 'GRPO No', 'GRPO Number'],
        grpoDate: ['GRPO Date', 'Receipt Date'],
        qtyReceived: ['GRPO Qty (this receipt)', 'GRPO Qty', 'Qty Received'],
        qtyReturned: ['Returned Qty (this receipt)', 'Returned Qty', 'Qty Returned'],
        returnDate: ['Return Date'],
        origin: ['Origin', 'Import/Local', 'U_Origin'],
      },
      po: {
        poDoc: ['PO No', 'PO Number', 'PO DocNum', 'DocNum', 'PO_DocNum', 'DocEntry'],
        poLine: ['PO Line', 'LineNum', 'Line', 'PO_LineNum'],
        poDate: ['PO Date', 'DocDate', 'Posting Date', 'PO_DocDate'],
        vendorCode: ['Vendor Code', 'CardCode', 'BP Code', 'Supplier Code'],
        vendorName: ['Vendor Name', 'CardName', 'BP Name', 'Supplier Name'],
        vendorGroup: ['Vendor Group', 'GroupName', 'BP Group', 'Group'],
        itemCode: ['Item Code', 'ItemCode', 'Item No'],
        itemName: ['Item Name', 'Dscription', 'ItemName', 'Description', 'Item Description'],
        level1: ['Level 1', 'Level1', 'L1', 'U_Level1', 'Material Level 1'],
        level2: ['Level 2', 'Level2', 'L2', 'U_Level2', 'Material Level 2'],
        level3: ['Level 3', 'Level3', 'L3', 'U_Level3', 'Material Level 3'],
        level4: ['Level 4', 'Level4', 'L4', 'U_Level4', 'Material Level 4'],
        origin: ['Origin', 'Import/Local', 'Import Local', 'U_Origin', 'Source'],
        qtyOrdered: ['Qty Ordered', 'Quantity', 'Qty', 'Ordered Qty'],
        lineValue: ['Line Total', 'LineTotal', 'Total (LC)', 'Value', 'Amount'],
        openQty: ['Open Qty', 'OpenQty', 'Remaining Qty'],
        prDoc: ['PR No', 'PR Number', 'PR DocNum', 'BaseRef'],
        prDate: ['PR Date', 'PR DocDate', 'Request Date'],
        prRequiredDate: ['Required Date', 'PR Required Date', 'ReqDate', 'PQTReqDate'],
      },
      grpo: {
        grpoDoc: ['GRPO No', 'GRPO Number', 'GRPO DocNum', 'DocNum'],
        grpoLine: ['GRPO Line', 'LineNum', 'Line'],
        grpoDate: ['GRPO Date', 'DocDate', 'Receipt Date', 'Posting Date'],
        vendorCode: ['Vendor Code', 'CardCode', 'BP Code'],
        vendorName: ['Vendor Name', 'CardName', 'BP Name'],
        itemCode: ['Item Code', 'ItemCode'],
        qtyReceived: ['Qty Received', 'Quantity', 'Qty', 'Received Qty'],
        poDoc: ['PO No', 'Base PO', 'BaseRef', 'Base Ref', 'PO Number'],
        poLine: ['PO Line', 'BaseLine', 'Base Line'],
      },
      returns: {
        returnDoc: ['Return No', 'DocNum', 'Return Number'],
        returnDate: ['Return Date', 'DocDate', 'Posting Date'],
        vendorCode: ['Vendor Code', 'CardCode', 'BP Code'],
        itemCode: ['Item Code', 'ItemCode'],
        qtyReturned: ['Qty Returned', 'Quantity', 'Qty', 'Returned Qty'],
      },
    },
    importValues: ['import', 'impor', 'i', 'imp', 'overseas', 'foreign'],
    localValues: ['local', 'lokal', 'l', 'loc', 'domestic'],
    defaultOrigin: 'Local',
    // The PRD ranks material vendors. With these groups left out, the extract's
    // medians reproduce the PRD allowance examples (Hardware 19/42, Packaging 18/29, Sparepart 6/35).
    excludedVendorGroups: ['V. Service & Maintenance', 'V. Fixed Asset', 'V. GA Material', 'V. Internal Group', 'V. Expedition'],
    dateOrder: 'auto',
  },

  labels: {
    app: { title: 'Vendor Performance', subtitle: 'Material vendors ranked on SAP B1 purchasing data' },
    tabs: { scorecard: 'Scorecard', issues: 'Vendors with issues', config: 'Configuration', how: 'How scoring works', upload: 'Upload' },
    scope: {
      vendorGroup: 'Vendor group', allGroups: 'All groups', chooseFirst: 'Choose level {n} first', clear: 'Clear',
      level1: 'Level 1 · Item Group', level2: 'Level 2', level3: 'Level 3', level4: 'Level 4',
      all: 'All',
      tip: 'Scope = vendor group × material path. Ranks, medians, quartiles and the spend share are all computed inside this scope.',
    },
    filters: {
      find: { label: 'Find vendor', tip: 'Matches vendor name or code. Does not change ranks.' },
      minPoLines: { label: 'Min PO lines', tip: 'Hides vendors with fewer PO lines in scope. With "Rank among: vendors passing Min PO lines", ranks are computed after this filter.' },
      reviewOnly: { label: 'Review threshold only', tip: 'Only vendors at or above the review threshold (PO lines and/or value, set on Configuration).' },
      top80: { label: 'Top {topSharePct} of spend', tip: 'Only the largest vendors that together make up the configured share of scope spend.' },
      issueOnly: { label: 'Only vendors with an issue', tip: 'Only vendors carrying at least one issue flag.' },
      stillInUse: { label: 'Still in use only', tip: 'Only vendors whose last PO is within the still-in-use window of the newest PO in the data.' },
      severity: { label: 'Severity', tip: 'Serious = at least one flag of serious severity.' },
      severityAny: 'Any',
      severitySerious: 'Serious',
      issueType: { label: 'Issue type', tip: 'Only vendors carrying this flag.' },
      issueTypeAny: 'Any issue',
    },
    modes: { plain: 'Plain', ranks: 'Ranks', tip: 'Plain shows a verdict word and the measured value; Ranks shows each criterion rank inside the scope.' },
    actions: {
      copyShortlist: 'Copy shortlist',
      copied: 'Copied {count} rows',
      copyFallbackTitle: 'Copy shortlist',
      copyFallbackHint: 'The clipboard is blocked in this browser. Select all and copy (Ctrl+C), then paste into Excel.',
      close: 'Close',
      save: 'Save configuration',
      reset: 'Reset to defaults',
      discard: 'Discard changes',
      exportJson: 'Export JSON',
      importJson: 'Import JSON',
      loadData: 'Load data',
      loadDemo: 'Load demo data',
      clearData: 'Clear data',
    },
    coverage: {
      title: 'PO-link coverage',
      template: '{linked} of {total} receipts in scope carry a lead time ({pct}). The rest are left out of lead time and on time.',
      exclusionsTitle: 'Exclusions',
      reasons: {
        noPoLink: 'Receipt has no base PO',
        poNotFound: 'Base PO line not found in the PO extract',
        negativeDays: 'Receipt dated before its PO or PR',
        noPrDate: 'No PR date (PR → GRPO clock only)',
      },
    },
    legend: {
      title: 'Legend',
      verdicts: 'Verdict words',
      quartiles: 'Cell colour',
      flags: 'Issue flags',
      marks: 'Marks',
      thresholdDot: 'At or above the review threshold',
      thinMark: 'Fewer receipts than the thin-sample guard; flags other than Returns are held back',
      thinMarkLabel: 'thin',
      groupChip: 'Vendor group',
      stillInUse: 'Still in use',
      notInUse: 'No longer used',
    },
    table: {
      empty: 'No vendor matches these filters. Lower Min PO lines or clear the search to widen the list.',
      emptyIssues: 'No problem vendors match. This list collects vendors with late, slow, short or returned deliveries so they can be actioned.',
      rows: 'rows',
      of: 'of',
      perPage: 'Rows per page',
      prev: 'Previous',
      next: 'Next',
      daysAgo: '{days} d ago',
      noIssues: '—',
    },
    detail: {
      issues: 'Issues',
      lastPo: 'Last PO',
      lastGrpo: 'Last GRPO',
      status: 'Status',
      openRows: 'Open rows',
      scoreRank: 'Score and rank',
      criteria: 'Criteria',
      profiles: 'Lead-time profiles',
      topItems: 'Top 5 items',
      relationship: 'Relationship',
      firstPo: 'First PO',
      firstGrpo: 'First GRPO',
      span: 'Active span',
      measured: 'Measured',
      rank: 'Rank',
      weight: 'Weight',
      quartile: 'Quartile',
      receipts: 'receipts',
      item: 'Item',
      value: 'Value',
      qty: 'Qty',
      measures: { prToRequired: 'PR → Required date', prToPo: 'PR → PO', poToGrpo: 'PO → GRPO' },
      noProfile: 'No receipts with both dates for this measure.',
    },
    config: {
      groupsTitle: 'Vendor groups in the platform',
      groupsHint: 'Groups switched off are left out of every scope, median, allowance and rank. Defaults leave out non-material groups (the PRD ranks material vendors). Count = PO lines.',
      allowanceTitle: 'Lead-time allowance',
      allowanceHint: 'Days per Level 1 material and origin. Empty = the extract median. A receipt inside its allowance is on time.',
      material: 'Level 1 material',
      median: 'Median',
      p90: 'P90',
      onTimeNow: 'On time now',
      impactTitle: 'Impact of unsaved changes',
      impactOnTime: 'On-time rate',
      impactLate: 'Vendors flagged Late',
      impactProblem: 'Problem vendors in use',
      impactTop: 'Top-ranked vendor',
      onTimeTitle: 'On-time rule',
      clock: 'Clock',
      clockPO: 'PO → GRPO',
      clockPR: 'PR → GRPO',
      requiredDate: 'Arriving by the required date always counts as on time',
      issuesTitle: 'Issue rules',
      latePct: 'Late below (% on time)',
      slowMultiple: 'Slow above (× scope median)',
      shortFillPct: 'Short fill below (%)',
      shortFillSeriousPct: 'Short fill serious below (%)',
      returnsPct: 'Returns above (%)',
      stillInUseDays: 'Still in use within (days of newest PO)',
      thinSample: 'Thin sample below (receipts)',
      verdictTitle: 'Verdict words',
      binsTitle: 'Bin edges',
      binsHint: 'Upper edge of each bin in days. The last bin is open-ended.',
      addEdge: 'Add edge',
      resetBins: 'Reset',
      weightsTitle: 'Criterion weights',
      weightsHint: '0–5 each. All zero is blocked because no vendor could be ranked.',
      weightsZero: 'At least one weight must be above zero.',
      reviewTitle: 'Review threshold',
      reviewLines: 'Minimum PO lines',
      reviewValue: 'Minimum value',
      reviewCombine: 'Vendor qualifies when',
      reviewAny: 'either is met',
      reviewAll: 'both are met',
      scoringTitle: 'Ranking method',
      tieMethod: 'Ties',
      missingRank: 'Vendor with no value',
      rankPopulation: 'Rank among',
      leadStat: 'Lead-time statistic',
      capFill: 'Cap received at ordered per PO line',
      tilesTitle: 'Cards',
      tilesHint: 'Label, metric, format, hint template and accent rule of every stat card. Placeholders: {metricKey}.',
      columnsTitle: 'Columns',
      columnsHint: 'Header label, tooltip text and visibility. # and Vendor stay frozen on the left.',
      labelsTitle: 'Labels & text',
      labelsHint: 'Every string shown in the platform. Search by key or text.',
      formatTitle: 'Number & date format',
      jsonTitle: 'Configuration file',
      jsonHint: 'Export to share a configuration with a colleague or keep it with the review-cycle evidence. Import replaces the draft; save to apply.',
      unsaved: 'Unsaved changes',
      saved: 'Saved in this browser',
      savedAt: 'Configuration saved',
      search: 'Search labels',
      sectionPolicy: 'Policy',
      sectionPresentation: 'Presentation',
      sectionAdvanced: 'Advanced',
    },
    how: {
      title: 'How scoring works',
      intro: 'A vendor\'s score is the weighted sum of its ranks on three criteria inside the selected scope. The lowest score is the best vendor. All measures are computed per vendor over the rows in scope (vendor group × Level 1–4 path).',
    },
    upload: {
      title: 'Upload SAP extract',
      flatTitle: 'Combined SAP extract',
      flatHint: 'One row per GRPO receipt with PR, PO and return fields on the same row (PO lines not yet received appear once, without GRPO fields).',
      intro: 'Load the combined SAP B1 extract, or the three separate extracts, as CSV or Excel. Columns are matched by header name; adjust the mapping if a column is not found. Data stays in this browser.',
      poTitle: 'Purchase order lines',
      poHint: 'OPOR / POR1 joined to OPRQ / PRQ1 for PR date and required date.',
      grpoTitle: 'Goods receipt PO lines',
      grpoHint: 'OPDN / PDN1 with the base PO number and line.',
      returnsTitle: 'Goods returns',
      returnsHint: 'ORPD / RPD1. Optional.',
      chooseFile: 'Choose file',
      sheet: 'Sheet',
      required: 'required',
      optional: 'optional',
      notMapped: '— not mapped —',
      rowsRead: '{rows} rows read',
      reconcileTitle: 'Reconciliation',
      reconcileHint: 'Check these totals against the source workbook before relying on the scorecard.',
      currentTitle: 'Loaded data',
      source: 'Source',
      loadedAt: 'Loaded',
      demoNote: 'Synthetic demo data. Replace it with the SAP extract before using the scorecard for decisions.',
      missingRequired: 'Map every required field before loading.',
    },
    empty: {
      noData: 'No purchasing data loaded yet',
      noDataHint: 'The scorecard ranks vendors from the SAP B1 PO, GRPO and return extracts. Upload them, or load the demo data to explore the platform.',
    },
  },
}
